export { default as SettingsPage } from './SettingsPage'
export { default as OrganizationSettingsPage } from './OrganizationSettingsPage.js'
export { default as TagSettingsPage } from './TagSettingsPage'
export { default as TeamMembersSettingsPage } from './TeamMembersSettingsPage'
export { default as GradYearsSettingsPage } from './GradYearsSettingsPage'
export { default as PositionsSettingsPage } from './PositionsSettingsPage'
export { default as StatusesSettingsPage } from './StatusesSettingsPage'
export { default as RanksSettingsPage } from './RanksSettingsPage'
export { default as SnippetsSettingsPage } from './SnippetsSettingsPage'
export { default as BoardSettingsPage } from './BoardSettingsPage'
// export { default as PlaceholdersSettingsPage } from './PlaceholdersSettingsPage'
// export { default as SendCoachTypesSettingsPage } from './SendCoachTypesSettingsPage'
// export { default as PeopleTypesSettingsPage } from './PeopleTypesSettingsPage'